### ISSUE TITLE
data dir is missing

### ISSUE THREAD

**Issue by LooOOooM** [F1LT3R/bitcoin-scraper#3]
I installed bitcoin-scrapper from scratch:

I get an error saying that it cannot open the bitstamp.log file wich it want to create. reason for that is that there is no "data" dir. an mkdir data fixed the problem for me

**Comment by squk** [comment]
The README addresses this. This is not an issue. Tracking an empty directory wouldn't be useful in a repo.

**Comment by F1LT3R** [comment]
fixed
